source 'https://github.com/CocoaPods/Specs.git'

deployment_target = '12.0'
platform :ios, deployment_target

inhibit_all_warnings!
use_frameworks!

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '11.0'
    end
  end
end


target 'SnapKitDemo' do
  pod 'SnapKit'

end
